/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DofusCraftHelper;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.plaf.basic.BasicArrowButton;
import javax.swing.plaf.basic.BasicSpinnerUI;

/**
 *
 * @author antoi
 */
public class Dialogue extends javax.swing.JFrame {

    String strIngr[] = {"", "", "", "","", "", "", ""};
    String strNbre[] = {"", "", "", "","", "", "", ""};
    String strType[] = {"","","","","", "", "", ""};
    String IdIdole = "";
    
    /**
     * Creates new form Dialogue
     */
    public Dialogue(String IDidole, String NOMidole) {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        jPanel2.setBackground(new Color(201,191,156));
        jSpinner1.getEditor().getComponent(0).setBackground(new Color(181,171,141));
        jSpinner1.setBorder(BorderFactory.createLineBorder(new Color(86,86,86)));
        ((DefaultEditor) jSpinner1.getEditor()).getTextField().setEditable(false);
        jSpinner1.setUI(new MySpinnerUI());
        
        this.setIconImage(new ImageIcon(getClass().getResource
            ("/Ressources/logoDofus.png")).getImage());
        
        IdIdole = IDidole;
        
        BDD bdd = new BDD();
        bdd.getRecette(this);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Recette de " + NOMidole);
        JLnomIdole.setText(NOMidole + "  x");
        setResizable(false);
        
        Ingr1.setText(strIngr[0]);
        Ingr2.setText(strIngr[1]);
        Ingr3.setText(strIngr[2]);
        Ingr4.setText(strIngr[3]);
        Ingr5.setText(strIngr[4]);
        Ingr6.setText(strIngr[5]);
        Ingr7.setText(strIngr[6]);
        Ingr8.setText(strIngr[7]);
        
        Nbre1.setText(strNbre[0]);
        Nbre2.setText(strNbre[1]);
        Nbre3.setText(strNbre[2]);
        Nbre4.setText(strNbre[3]);
        Nbre5.setText(strNbre[4]);
        Nbre6.setText(strNbre[5]);
        Nbre7.setText(strNbre[6]);
        Nbre8.setText(strNbre[7]);
        
        Type1.setText(strType[0]);
        Type2.setText(strType[1]);
        Type3.setText(strType[2]);
        Type4.setText(strType[3]);
        Type5.setText(strType[4]);
        Type6.setText(strType[5]);
        Type7.setText(strType[6]);
        Type8.setText(strType[7]);
            
    
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btAnnuler = new javax.swing.JButton();
        Ingr4 = new javax.swing.JTextField();
        Nbre4 = new javax.swing.JTextField();
        Type4 = new javax.swing.JTextField();
        Type3 = new javax.swing.JTextField();
        Nbre3 = new javax.swing.JTextField();
        Ingr3 = new javax.swing.JTextField();
        Ingr2 = new javax.swing.JTextField();
        Nbre2 = new javax.swing.JTextField();
        Type2 = new javax.swing.JTextField();
        Type1 = new javax.swing.JTextField();
        Nbre1 = new javax.swing.JTextField();
        Ingr1 = new javax.swing.JTextField();
        JLnomIdole = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Ingr5 = new javax.swing.JTextField();
        Nbre5 = new javax.swing.JTextField();
        Type5 = new javax.swing.JTextField();
        Type6 = new javax.swing.JTextField();
        Nbre6 = new javax.swing.JTextField();
        Ingr6 = new javax.swing.JTextField();
        Ingr7 = new javax.swing.JTextField();
        Nbre7 = new javax.swing.JTextField();
        Type7 = new javax.swing.JTextField();
        Type8 = new javax.swing.JTextField();
        Nbre8 = new javax.swing.JTextField();
        Ingr8 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAnnuler.setBackground(new java.awt.Color(255, 97, 0));
        btAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        btAnnuler.setText("Retour");
        btAnnuler.setToolTipText("");
        btAnnuler.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 86, 86), 1, true));
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        Ingr4.setEditable(false);
        Ingr4.setBackground(new java.awt.Color(181, 171, 141));
        Ingr4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Ingr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingr4ActionPerformed(evt);
            }
        });

        Nbre4.setEditable(false);
        Nbre4.setBackground(new java.awt.Color(181, 171, 141));
        Nbre4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbre4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Nbre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nbre4ActionPerformed(evt);
            }
        });

        Type4.setEditable(false);
        Type4.setBackground(new java.awt.Color(181, 171, 141));
        Type4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Type3.setEditable(false);
        Type3.setBackground(new java.awt.Color(181, 171, 141));
        Type3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Nbre3.setEditable(false);
        Nbre3.setBackground(new java.awt.Color(181, 171, 141));
        Nbre3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbre3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Nbre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nbre3ActionPerformed(evt);
            }
        });

        Ingr3.setEditable(false);
        Ingr3.setBackground(new java.awt.Color(181, 171, 141));
        Ingr3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Ingr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingr3ActionPerformed(evt);
            }
        });

        Ingr2.setEditable(false);
        Ingr2.setBackground(new java.awt.Color(181, 171, 141));
        Ingr2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Ingr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingr2ActionPerformed(evt);
            }
        });

        Nbre2.setEditable(false);
        Nbre2.setBackground(new java.awt.Color(181, 171, 141));
        Nbre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Type2.setEditable(false);
        Type2.setBackground(new java.awt.Color(181, 171, 141));
        Type2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Type2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type2ActionPerformed(evt);
            }
        });

        Type1.setEditable(false);
        Type1.setBackground(new java.awt.Color(181, 171, 141));
        Type1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Nbre1.setEditable(false);
        Nbre1.setBackground(new java.awt.Color(181, 171, 141));
        Nbre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Ingr1.setEditable(false);
        Ingr1.setBackground(new java.awt.Color(181, 171, 141));
        Ingr1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Ingr1.setMinimumSize(new java.awt.Dimension(20, 20));
        Ingr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingr1ActionPerformed(evt);
            }
        });

        JLnomIdole.setText("Wakata Bom Bom Youpy ");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        Ingr5.setEditable(false);
        Ingr5.setBackground(new java.awt.Color(181, 171, 141));
        Ingr5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Ingr5.setMinimumSize(new java.awt.Dimension(20, 20));
        Ingr5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingr5ActionPerformed(evt);
            }
        });

        Nbre5.setEditable(false);
        Nbre5.setBackground(new java.awt.Color(181, 171, 141));
        Nbre5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbre5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Type5.setEditable(false);
        Type5.setBackground(new java.awt.Color(181, 171, 141));
        Type5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Type6.setEditable(false);
        Type6.setBackground(new java.awt.Color(181, 171, 141));
        Type6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Type6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type6ActionPerformed(evt);
            }
        });

        Nbre6.setEditable(false);
        Nbre6.setBackground(new java.awt.Color(181, 171, 141));
        Nbre6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbre6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Ingr6.setEditable(false);
        Ingr6.setBackground(new java.awt.Color(181, 171, 141));
        Ingr6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Ingr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingr6ActionPerformed(evt);
            }
        });

        Ingr7.setEditable(false);
        Ingr7.setBackground(new java.awt.Color(181, 171, 141));
        Ingr7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Ingr7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingr7ActionPerformed(evt);
            }
        });

        Nbre7.setEditable(false);
        Nbre7.setBackground(new java.awt.Color(181, 171, 141));
        Nbre7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbre7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Nbre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nbre7ActionPerformed(evt);
            }
        });

        Type7.setEditable(false);
        Type7.setBackground(new java.awt.Color(181, 171, 141));
        Type7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Type8.setEditable(false);
        Type8.setBackground(new java.awt.Color(181, 171, 141));
        Type8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Nbre8.setEditable(false);
        Nbre8.setBackground(new java.awt.Color(181, 171, 141));
        Nbre8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbre8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Nbre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nbre8ActionPerformed(evt);
            }
        });

        Ingr8.setEditable(false);
        Ingr8.setBackground(new java.awt.Color(181, 171, 141));
        Ingr8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Ingr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingr8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btAnnuler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(Ingr7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Nbre7))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Ingr5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Ingr6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nbre6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nbre5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(Ingr8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(Nbre8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Type5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Type6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Type7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Type8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Ingr3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nbre3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ingr1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ingr2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nbre2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nbre1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Ingr4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Nbre4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Type1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Type2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Type3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Type4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JLnomIdole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnomIdole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingr1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nbre1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nbre2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ingr2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ingr3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nbre3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Type3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingr4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nbre4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingr5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nbre5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nbre6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ingr6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ingr7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nbre7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Type7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingr8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nbre8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nbre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nbre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nbre4ActionPerformed

    private void Nbre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nbre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nbre3ActionPerformed

    private void Ingr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingr3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingr3ActionPerformed

    private void Ingr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingr2ActionPerformed

    private void Ingr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingr1ActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed

    private void Ingr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingr4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingr4ActionPerformed

    private void Type2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Type2ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        try {
            jSpinner1.commitEdit();
        } catch (Exception e ){

        }
        int multi = (Integer) jSpinner1.getValue();
        String total;
        int result;
        
        result = Integer.parseInt(strNbre[0]);
        result = result * multi;
        total = String.valueOf(result);
        Nbre1.setText(total);

        result = Integer.parseInt(strNbre[1]);
        result = result * multi;
        total = String.valueOf(result);
        Nbre2.setText(total);

        result = Integer.parseInt(strNbre[2]);
        result = result * multi;
        total = String.valueOf(result);
        Nbre3.setText(total);

        result = Integer.parseInt(strNbre[3]);
        result = result * multi;
        total = String.valueOf(result);
        Nbre4.setText(total);
        
        result = Integer.parseInt(strNbre[4]);
        result = result * multi;
        total = String.valueOf(result);
        Nbre5.setText(total);
        
        result = Integer.parseInt(strNbre[5]);
        result = result * multi;
        total = String.valueOf(result);
        Nbre6.setText(total);
        
        result = Integer.parseInt(strNbre[6]);
        result = result * multi;
        total = String.valueOf(result);
        Nbre7.setText(total);
        
        result = Integer.parseInt(strNbre[7]);
        result = result * multi;
        total = String.valueOf(result);
        Nbre8.setText(total);
        
    }//GEN-LAST:event_jSpinner1StateChanged

    private void Ingr5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingr5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingr5ActionPerformed

    private void Type6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Type6ActionPerformed

    private void Ingr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingr6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingr6ActionPerformed

    private void Ingr7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingr7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingr7ActionPerformed

    private void Nbre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nbre7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nbre7ActionPerformed

    private void Nbre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nbre8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nbre8ActionPerformed

    private void Ingr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingr8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingr8ActionPerformed

    //Couleurs Spinner
    public class MySpinnerUI extends BasicSpinnerUI {
        protected JButton createDecreaseButton(int orientation) {
            return new BasicArrowButton(orientation,
                                     (new Color(201,191,156)),
                                     (new Color(81,73,60)),
                                     (new Color(81,73,60)),
                                     (new Color(81,73,60)));
        }
        protected JButton createIncreaseButton(int orientation) {
    	    return new BasicArrowButton(orientation,
                                     (new Color(201,191,156)),
                                     (new Color(81,73,60)),
                                     (new Color(81,73,60)),
                                     (new Color(81,73,60)));
        }
    }
    
    public String delID;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dialogue("0", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ingr1;
    private javax.swing.JTextField Ingr2;
    private javax.swing.JTextField Ingr3;
    private javax.swing.JTextField Ingr4;
    private javax.swing.JTextField Ingr5;
    private javax.swing.JTextField Ingr6;
    private javax.swing.JTextField Ingr7;
    private javax.swing.JTextField Ingr8;
    private javax.swing.JLabel JLnomIdole;
    private javax.swing.JTextField Nbre1;
    private javax.swing.JTextField Nbre2;
    private javax.swing.JTextField Nbre3;
    private javax.swing.JTextField Nbre4;
    private javax.swing.JTextField Nbre5;
    private javax.swing.JTextField Nbre6;
    private javax.swing.JTextField Nbre7;
    private javax.swing.JTextField Nbre8;
    private javax.swing.JTextField Type1;
    private javax.swing.JTextField Type2;
    private javax.swing.JTextField Type3;
    private javax.swing.JTextField Type4;
    private javax.swing.JTextField Type5;
    private javax.swing.JTextField Type6;
    private javax.swing.JTextField Type7;
    private javax.swing.JTextField Type8;
    private javax.swing.JButton btAnnuler;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
